name: Build C portfolio

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc -Wall -Wextra -O2 portfolio.c -o portfolio
      - run: ./portfolio

